### PR TITLE
Updates example to cut out everything that doesn't show Nucleus, so that it's simpler and doesn't require a network connection.

### PR DESCRIPTION
**Pull request by rharter**
This updates the main example to make it cleaner, without extra items like retrofit or the need for a network connection.  This way the example is only showing off Nucleus, not other libraries or programming styles that might be foreign to some users.

The new sample still shows both an RX example and a regular one, saving state, a count of onTakeView, and how to pass events and data between the Activity and Presenter in both directions.

Todos:

* Add more examples to show working with Fragments and Views in addition to Activities
* Come up with a workflow that demonstrates the most common workflows.

### CODE REVIEW

**Comment by konmik** [comment]
Wow, a great contribution! :) I will take a look.

What is so bad in using network connection? I think retrofit is plain simple, so people should not be distracted off the example. I never had a device or emulator without a network connection

Common workflows? Whahaha, you don't know what I consider "common". Fragments and activities are not in this list. :D But you're right, a good example on fragments is needed. Probably I will even write NucleusFragmentStack or something.

**Comment by rharter** [comment]
The problem with network connection requirements for the sample, IMHO, is
that its just a barrier that isn't required. In my case, for instance, I've
got several test devices that I use which don't have Sim cards, if I'm at
home that's fine, but I don't connect them all to WiFi when I got to coffee
shops to work.

I'll admit this is largely personal preference, but I find the best samples
are ones that at least have a sample with the bare minimum required to
demonstrate the library, then perhaps others of common use cases.

Another thing to mention, I removed the package structure because a lot of
people view the samples on Github's web interface and its much easier when
you can quickly view all the files without needed to traverse packages.

**Comment by rharter** [comment]
Also, I agree about the common statement, but the goal is to make it as
accessible as possible for most people, and so standard examples should be
there.

Unless, of course, that's not the goal, which is totally fine, too. It is
your project after all :)

**Comment by konmik** [comment]
OK, so do not see a reason for replacing the current example.
I think that having a real (not fake) background task is important. :)
I appreciate your willingness to help. :)

I've seen your example and have a little notices, I hope they will help you.

1. Instead of `SystemClock.sleep(1500);` you could use `delay()` rx operator.

2. `ExampleRxPresenter.onPlanetClicked` controls View. In my introductory article I wrote that a Presenter should not control a view, so I would place the method into `ExampleRxActivity`, making code shorter and simpler to understand.

3. Prefix your callback methods with `on` instead of `show`. I know it is hard, it took a long time for me to get used to, but this way I show that this is just a callback method, but not a method of control. So code clearly shows that a presenter does not control a view.

**Pull request closed without merging**
