### PR TITLE
Adds Presenter Factory

### PR DESCRIPTION
**Pull request by rharter**
This moves the logic of reflectively creating the presenter into a presenter factory, so that that functionality can be customized.

In my case, I'm using Dagger to inject dependencies, and using a presenter factory allows me to inject the dependencies through the presenter constructor, without having to use a pseudo-singleton injector class.

The superclasses include the default `ReflectionPresenterFactory`, so they have the same out of the box functionality, but by extracting that logic out of the PresenterHelper, the user is offered much more flexibility.

Note:  I'm not sure how you're handling versioning, so I changed the dependencies in the support libraries and the examples to point to the snapshot version that I made and installed locally.  I didn't include that in this PR since that's a change that shouldn't go into production.

### CODE REVIEW

**Comment by konmik** [comment]
This looks exactly as something I was preparing for the next commit :+1: 

How the hell did you read my mind? :D

**Comment by konmik** [comment]
Just uploaded to sonatype. I think the 1.3.0 release will become available in a few hours.

**Comment by writtmeyer** [comment]
There it is! Thanks again!

**Comment by cavarzan** [comment]
@rharter did you have a example for using a presenter with custom constructor injected by dagger2?

**Comment by rharter** [comment]
I don't offhand, but there's nothing specific to Nucleus about that, You do it exactly the same way you would use dagger to create any other class.

In my case, I'm actually injecting the dependencies through the constructor.  So my activity gets the dependencies via Dagger, and the factory method looks like this:

```java
@Override public PresenterFactory<StorePresenter> getPresenterFactory() {
    return new PresenterFactory<StorePresenter>() {
        @Override public StorePresenter createPresenter() {
            return new StorePresenter(storeApi, itemManager);
        }
    };
}
```

Using this factory, the presenter only gets recreated by Nucleus if it doesn't already exist, so you don't have to worry about the presenter lifecycle.

**Comment by konmik** [comment]
Here is my use case for factories:

``` java
public class BaseScreenView<PresenterType extends Presenter> extends NucleusLayout<PresenterType> {

    @Override
    public PresenterFactory<PresenterType> getPresenterFactory() {
        final PresenterFactory<PresenterType> superFactory = BaseScreenView.super.getPresenterFactory();
        return superFactory == null ? null : new PresenterFactory<PresenterType>() {
            @Override
            public PresenterType createPresenter() {
                PresenterType presenter = superFactory.createPresenter();
                ((PresenterInjector)getContext()).injectIntoPresenter(presenter);
                return presenter;
            }
        };
    }
```

I do not inject activity dependencies (this will cause memory leaks!) but dependencies that are associated with activity arguments. I have an activity that should show information from database for specific user. I pass userId via intent and get database scope for the account. Then I inject that database interface into presenter, so presenter is limited by only one user scope.

**Comment by cavarzan** [comment]
@rharter I understand, just pass instantiated dependencies into the constructor.

@konmik so `injectIntoPresenter` is the code that create a new instance and inject into the component? It's an application module or `PresenterInjector` knows the module to be injected?

I'm using this approach:

```
    @Inject 
    MyPresenter presenter;
    ...
    @Override
    public PresenterFactory<MyPresenter> getPresenterFactory() {
        return () -> {
            ((MainActivity)getActivity()).getComponent().inject(MyFragment.this);
            return presenter;
        };
    }
```

But since I need to have the activity to get the Component. `getPresenterFactory` is called in `onCreate` sometimes the Fragment hasn't attached to the Activity.

**Comment by konmik** [comment]
Here is a simplified example with Dagger1 (I currently switching to Dagger2):

``` java
public class MainActivity extends Activity implements PresenterInjector {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        accountObjectGraph = App.obtainAccountGraph(accountId);
   }
    @Override
    public void injectIntoPresenter(Presenter presenter) {
        accountObjectGraph.inject(presenter);
    }
```

**Comment by rharter** [comment]
I don't use Fragments much in my scenario, so I haven't run into that.  I have felt that the PresenterFactory is called quite early in the process though, not leaving much room for things like injections.  In my activities, I've resorted to calling inject before calling `super.onCreate()`.

Specifically with Dagger2, you don't have to inject the object to get the values.  Simply change your component to have a `MyPresenter myPresenter()` method and you can call that directly on the component.  That doesn't really solve the issue, since you still need to get the component, but it cleans up the Fragment (or Activity) code a bit.

@konmik Along these lines, I've been thinking, is there a reason not to make the presenter generation lazy?  For instance, if we defer getting the presenter from the manager until the first time `getPresenter()` is called, that would more easily allow users to follow a standard call-super-inject-initialize pattern.  At the latest this would happen in `onResume()`, but could be earlier if the user calls `getPresenter()` during `onCreate()`.

Only challenge I could see is storing the savedInstanceState bundle for when it is called.

**Comment by cavarzan** [comment]
@konmik thanks! In case of dagger2, using activity modules and injecting dependencies into some fragment, you will need the activity to inject the presenter (if you want to use the same activity scope). So at this point, the component needs to be injected before `onCreate()`.

@rharter Nice! I inject the module before call super.onCreate(bundle) and works:

```
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        inject();
        super.onCreate(savedInstanceState);
    }
```

But your suggestion for lazy loading seems to be a nice approach.

**Comment by konmik** [comment]
@rharter Lazy instantiation looks like a very good idea. We will just need to call `getPresenter()` during `onResume()` for the case when nothing else called `getPresenter()`.

P.S. I normally use Nucleus without fragments, now I'm trying to figure out how to build a reliable fragment stack. This is not an easy task. :D

**Comment by konmik** [comment]
I'll take the lazy instantiation ticket :D

**Pull request merged**
