### PR TITLE
Repro for #147

### PR DESCRIPTION
**Pull request by TWiStErRob**
First I started building a separate project, but then I realized you had examples already. So I just upgraded your repo instead to the latest build tools and SDK, enabled ProGuard for example's release builds and then manually added a dependency higher than what Nucleus is built with to repro #147.

(Note: the upgrade is not fully complete, there are some warnings as build (Jack, Android deprecations and Gradle deprecations), but everything seems to work for now.)

### CODE REVIEW

**Comment by konmik** [comment]
I couldn't merge it because of irrelevant modifications, but thanks for the reproducible example anyway!

**Comment by TWiStErRob** [comment]
I can drop last commit, or the mods that you think are irrelevant, just comment which ones.

**Comment by TWiStErRob** [comment]
Ah, I see, proguard :)

**Comment by konmik** [comment]
There were also gradle script changes, okhttp, apt, and the PR didn't solve the problem :) I needed it to be solved for both - master and rx2 branches.

**Pull request closed without merging**
