### PR TITLE
Add isUnsubscribed method

### PR DESCRIPTION
**Pull request by inorichi**
As you said to include this method for the next version, I added it. :)

Also, I created a wiki page for using restartables, I hope it helps people to get started with Nucleus. Please take a look https://github.com/konmik/nucleus/wiki/Restartables-examples

### CODE REVIEW

**Comment by konmik** [comment]
Hmm, nice :) How about some tests? ;)

**Comment by konmik** [comment]
I would also keep isUnsubscribed instead of isSubscriber to be completely idiomatic with RxJava (even if it suck here :D )

**Comment by inorichi** [comment]
Okay, done. Are the tests good?

**Comment by konmik** [comment]
This is great! :) Thanks.

**Pull request merged**
