### PR TITLE
Update android sdk and gradle build tools version.

### PR DESCRIPTION
**Pull request by IgorGanapolsky**
Use common ext block.

### CODE REVIEW

**Comment by rharter** [comment]
+1 This is a much cleaner way to handle these dependencies with so many modules.

**Comment by konmik** [comment]
OK, I will need to test it and then merge if everything is ok.

**Comment by konmik** [comment]
It works!

THANK YOU! :)

**Comment by IgorGanapolsky** [comment]
@konmik Thanks for the framework.  Have some @changetip $1 bitcoin on me.

**Comment by changetip** [comment]
Hi @konmik, @IgorGanapolsky sent you a Bitcoin tip worth 4,253 bits ($1.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/835913)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Pull request merged**
